#!/usr/bin/env python3
"""Fit and pack Cartesian Chebyshev models for the three centaurs."""

from __future__ import annotations

import argparse
import base64
import gc
from pathlib import Path
import struct

import numpy as np


AU_KM = 149597870.7
START_JD = 625295.0
END_JD = 2816795.0
TICK_DAYS = 0.125 * 365.25
TICK_COUNT = 48000
INITIAL_TICKS = 40
DEGREE = 7
MAX_POSITION_ERROR_KM = 5000.0
BODIES = ("chiron", "pholus", "nessus")


def load_samples(path):
    """Return alternating one-day samples for fitting and held-out checks."""

    with np.load(path) as source:
        all_jd = source["jd"]
        first = np.searchsorted(all_jd, START_JD)
        last = np.searchsorted(all_jd, END_JD, side="right")
        indices = np.arange(first + 1, last - 1, 2)
        return np.asarray(all_jd[indices]), np.asarray(source["pos_helio_au"][indices])


def fit_interval(jd, truth, start_tick, end_tick):
    start = START_JD + start_tick * TICK_DAYS
    end = START_JD + end_tick * TICK_DAYS
    last = end_tick == TICK_COUNT
    indices = np.flatnonzero((jd >= start) & ((jd <= end) if last else (jd < end)))
    training_local = np.arange(0, len(indices), 2)
    if training_local[-1] != len(indices) - 1:
        training_local = np.append(training_local, len(indices) - 1)
    training = indices[training_local]
    train_x = (2 * jd[training] - start - end) / (end - start)
    validation_x = (2 * jd[indices] - start - end) / (end - start)
    prediction = np.empty((len(indices), 3))
    coefficients_by_coordinate = []
    for coordinate in range(3):
        degree = min(DEGREE, len(training) - 1)
        coefficients = np.polynomial.chebyshev.chebfit(
            train_x, truth[training, coordinate], degree,
        ).astype("<f4")
        coefficients = np.pad(coefficients, (0, DEGREE + 1 - len(coefficients)))
        coefficients_by_coordinate.append(coefficients)
        prediction[:, coordinate] = np.polynomial.chebyshev.chebval(
            validation_x, coefficients,
        )
    held_out = np.ones(len(indices), dtype=bool)
    held_out[training_local] = False
    error_km = np.linalg.norm(
        prediction[held_out] - truth[indices][held_out], axis=1,
    ) * AU_KM
    return coefficients_by_coordinate, error_km


def fit_body(body, canonical_dir):
    print(f"{body}: loading samples", flush=True)
    jd, truth = load_samples(canonical_dir / f"{body}.npz")
    accepted = []
    stack = [
        (tick, min(tick + INITIAL_TICKS, TICK_COUNT))
        for tick in range(0, TICK_COUNT, INITIAL_TICKS)
    ]

    while stack:
        start_tick, end_tick = stack.pop()
        coefficients, error_km = fit_interval(jd, truth, start_tick, end_tick)
        if np.max(error_km) > MAX_POSITION_ERROR_KM and end_tick - start_tick > 1:
            middle = (start_tick + end_tick) // 2
            stack.extend(((middle, end_tick), (start_tick, middle)))
            continue
        if np.max(error_km) > MAX_POSITION_ERROR_KM:
            raise RuntimeError(
                f"{body} cannot meet {MAX_POSITION_ERROR_KM:g} km near tick {start_tick}"
            )
        accepted.append((start_tick, coefficients, error_km))

    accepted.sort(key=lambda item: item[0])
    packed = bytearray()
    all_error = []
    for start_tick, coefficients_by_coordinate, error_km in accepted:
        packed += struct.pack("<H", start_tick)
        for coefficients in coefficients_by_coordinate:
            packed += np.asarray(coefficients, dtype="<f4").tobytes()
        all_error.extend(error_km.tolist())
    all_error = np.asarray(all_error)
    print(
        f"{body}: segments={len(accepted)}, rms={np.sqrt(np.mean(all_error**2)):.3f} km, "
        f"p99={np.percentile(all_error, 99):.3f} km, max={np.max(all_error):.3f} km, "
        f"bytes={len(packed):,}",
        flush=True,
    )
    return bytes(packed), len(accepted)


def write_module(path, data, counts):
    encoded = base64.b64encode(data).decode("ascii")
    source = (
        "// Generated by packages/asteroids/tools/generate-centaur-asteroid-series.py; do not edit.\n"
        f"export const CENTAUR_ASTEROID_COUNTS = Object.freeze({list(counts)!r});\n"
        f"export const CENTAUR_ASTEROID_DATA_BASE64 = '{encoded}';\n"
    )
    path.write_text(source, encoding="ascii")
    print(f"{path}: {len(data):,} binary bytes -> {len(source):,} JavaScript bytes")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("canonical_dir", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    chunks = []
    counts = []
    for body in BODIES:
        chunk, count = fit_body(body, args.canonical_dir)
        chunks.append(chunk)
        counts.append(count)
        gc.collect()
    write_module(args.output, b"".join(chunks), counts)


if __name__ == "__main__":
    main()
