#!/usr/bin/env python3
"""Pack the offline lightweight asteroid fits into Base64 ES modules."""

from __future__ import annotations

import argparse
import base64
import importlib.util
import struct
from pathlib import Path


STABLE_BODIES = ("ceres", "pallas", "juno", "vesta", "eros", "lilith_1181")
EXPECTED_FORMAT = "lunaeph-lite-asteroid-poisson-v1-experiment"


def load_python_payload(path: Path):
    spec = importlib.util.spec_from_file_location("lite_asteroid_coefficients", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.LITE_ASTEROID_COEFFICIENTS


def pack_stable(payload) -> bytes:
    expected_metadata = {
        "format": EXPECTED_FORMAT,
        "frame": "heliocentric-icrf",
        "coordinates": "osculating-elements",
        "interval_years": [-3000, 3000],
        "segment_years": 600,
        "terms": 64,
    }
    for key, expected in expected_metadata.items():
        if payload.get(key) != expected:
            raise ValueError(f"unexpected {key}: {payload.get(key)!r}")
    packed = bytearray()
    for body in STABLE_BODIES:
        models = payload["bodies"][body]
        if len(models) != 10:
            raise ValueError(f"{body} must contain ten 600-year segments")
        for model in models:
            series = model["series"]
            frequencies = series["frequencies_cycles_per_year"]
            coefficients = series["coefficients"]
            if len(frequencies) != 64 or len(coefficients) != 390:
                raise ValueError(f"unexpected model shape for {body}")
            packed += struct.pack("<dd", series["epoch_jd"], series["half_span_days"])
            packed += struct.pack(f"<{len(frequencies)}f", *frequencies)
            flattened = [value for row in coefficients for value in row]
            packed += struct.pack(f"<{len(flattened)}f", *flattened)
    return bytes(packed)


def write_module(path: Path, name: str, data: bytes) -> None:
    encoded = base64.b64encode(data).decode("ascii")
    source = (
        "// Generated by packages/asteroids/tools/generate-asteroid-series.py; do not edit.\n"
        f"export const {name} = '{encoded}';\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="ascii")
    print(f"{path}: {len(data):,} binary bytes -> {len(source):,} JavaScript bytes")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    write_module(args.output, "STABLE_ASTEROID_DATA_BASE64", pack_stable(load_python_payload(args.source)))


if __name__ == "__main__":
    main()
